### ISSUE TITLE
Set `babelrc` to false for the react-hot-loader section

### ISSUE THREAD

**Issue by bebraw** [pmedianetwork/webpack-config#21]
---

PR # (fill in once PR number is available)

---

**About**

Make sure `babelrc: false,` is set for **babel-loader** in the `react-hot-loader` related section. Now it's not clear if it's using `.babelrc` or not in this case so it's likely best to be specific. Doing this might give a small performance boost (less to process).

**Possible implementation**

See above.

---

**Analysis**
_Should be filled out in the Analysis phase. Needs to be approved by another engineer before implementation starts. See [How to write a good analysis](http://handbook.adverity.net/kanban/#how-to-write-an-analysis-of-an-issue)_

---

**Tasks**
_A very detailed and technical list of tasks. Should be filled out after Analysis._

- [ ] task 1
- [ ] ..

**Comment by TkDodo** [comment]
can we close this since we are not using `react-hot-loader` anymore?

**Comment by bebraw** [comment]
Yeah, let's close.
