### ISSUE TITLE
refresh-on-fail for hot reloading

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/webpack-config#32]
---

PR # (fill in once PR number is available)

---

**About**

If hot reloading fails, it would be good to get a full page refresh (it would be better than waiting for the hmr for a long time just to find out it won't happen)

**Possible implementation**

from @bebraw 

> to do refresh on hmr fail, https://github.com/shellscape/webpack-plugin-serve/blob/master/lib/client/hmr.js#L39 would need to change. i'm discussing with the other authors if we should do hot: 'refresh-on-fail' kind of enum there (still waiting ok from andrew, the main author)

---

**Analysis**
_Should be filled out in the Analysis phase. Needs to be approved by another engineer before implementation starts. See [How to write a good analysis](http://handbook.adverity.net/kanban/#how-to-write-an-analysis-of-an-issue)_

---

**Tasks**
_A very detailed and technical list of tasks. Should be filled out after Analysis._

- [ ] task 1
- [ ] ..

**Comment by bebraw** [comment]
Thanks, I'll keep the conversation open and see if we can find a solution on **webpack-plugin-serve** end.

One option would be to fork and do the changes that are needed. It's better to get the changes to packages, though, as it's less maintenance to do.

**Comment by bebraw** [comment]
Just a quick update, I haven't heard back from Andrew yet. I hope all is ok over there (maybe he is just busy).

**Comment by bebraw** [comment]
@TkDodo Andrew would be ok with the change if we send a PR.

**Comment by TkDodo** [comment]
sounds good, would you be able to make the PR?

**Comment by bebraw** [comment]
@TkDodo Yup. Basically it's about adding one more flag and tuning https://github.com/shellscape/webpack-plugin-serve/blob/master/lib/client/hmr.js#L39 .

I'll give it a go today or so.

**Comment by bebraw** [comment]
You can track it here, https://github.com/shellscape/webpack-plugin-serve/pull/182 . I have an early, untested version there (needs some discussion).

**Comment by bebraw** [comment]
We did this in c6136aa but forgot to close.
