### ISSUE TITLE
Update to react-fast-refresh

### ISSUE THREAD

**Issue by bebraw** [pmedianetwork/webpack-config#4]
---

PR #7.

---

**About**

Fast Refresh is a new approach for HMR in React. See https://github.com/facebook/react/issues/16604 . The best part is that it doesn't require client-side `hot` anymore and it should be more reliable.

**Possible implementation**

https://github.com/pmmmwh/react-refresh-webpack-plugin

---

**Analysis**

For this change to be feasible, we should make sure the projects using **webpack-config** are using React 16.9 or newer already. Otherwise HMR would break after updating **webpack-config** in the projects.

---

**Tasks**

- [ ] Replace current HMR setup with the new plugin (inc. webpack and Babel) and remove the old one

**Comment by TkDodo** [comment]
@bebraw let's try this out please :)

**Comment by bebraw** [comment]
@TkDodo Which project would be a good starting point for testing this? I tried a setup in `adverity/adverity` but the complexity of the project (proxy setup) makes **react-refresh-webpack-plugin** fail. It can be so that it's not designed to be run behind a proxy.

**Comment by TkDodo** [comment]
would it work better in https://github.com/pmedianetwork/adverity-datatap ? I would prefer to start there anyways, because `develop` is already on react 16.13
