### ISSUE TITLE
centralized browserslist

### ISSUE THREAD

**Issue by TkDodo** [pmedianetwork/webpack-config#5]
---

PR #6

---

**About**

Create a centralized browserslist that we can share between the products because we only care about es6+ browsers

**Possible implementation**

This browserslist _should_ cover all browsers that support es6, which is in line with our feature detection:

```
"browserslist": [
    "chrome >= 55",
    "edge >= 15",
    "firefox >= 53",
    "opera >= 42",
    "safari >= 11",
    "ios >= 11"
  ],
```

---

**Analysis**
_Should be filled out in the Analysis phase. Needs to be approved by another engineer before implementation starts. See [How to write a good analysis](http://handbook.adverity.net/kanban/#how-to-write-an-analysis-of-an-issue)_

---

**Tasks**
_A very detailed and technical list of tasks. Should be filled out after Analysis._

- [ ] task 1
- [ ] ..

**Comment by bebraw** [comment]
Looks like https://www.npmjs.com/package/browserslist#shareable-configs is the ticket.
